import type { StyleDef } from './types'

export const EXTRA_STYLES: StyleDef[] = [
  {
    id: 'straight-rock',
    name: 'Rock',
    blurb: 'Solid backbeat and open guitar chords',
    bpm: [100, 124],
    moods: ['bright', 'epic'],
    bars: 2,
    swing: 0,
    sounds: { drums: 'acoustic-drums', bass: 'Bass', chords: 'Guitar', melody: 'Electric Piano' },
    progressions: [
      [0, 3, 4, 0],
      [0, 4, 5, 3],
      [5, 3, 0, 4],
    ],
    drums: {
      lines: {
        kick: ['x.......x.x.....', 'x.....x.x.......'],
        snare: ['....x.......x...'],
        hat: ['x.x.x.x.x.x.x.x.'],
        crash: ['o...............'],
      },
      fills: { snare: '....x.......x.ox', tom: '............o.ox' },
    },
    bass: {
      rhythms: ['x.......x.......', 'x...x...x...x...'],
      notes: { root: 8, fifth: 2, octave: 1 },
      approach: 0.15,
    },
    chords: { rhythms: ['x.......x.......', 'x...............'] },
    melody: { rhythms: ['x.......o...x...', '..x...o.x...o...'], leap: 0.15, register: 'mid' },
  },
  {
    id: 'disco',
    name: 'Disco',
    blurb: 'Dancing octaves and bright offbeats',
    bpm: [110, 122],
    moods: ['bright', 'soulful'],
    bars: 2,
    swing: 0.1,
    sounds: { drums: 'electronic-drums', bass: 'Bass', chords: 'Electric Piano', melody: 'Velvet Strings' },
    progressions: [
      [0, 5, 1, 4],
      [0, 3, 4, 3],
      [5, 3, 0, 4],
    ],
    drums: {
      lines: {
        kick: ['x...x...x...x...'],
        clap: ['....x.......x...'],
        hat: ['x.x.x.x.x.x.x.x.'],
        openHat: ['..x...x...x...x.'],
      },
      fills: { clap: '....x.......x.oo' },
    },
    bass: { rhythms: ['x.x.x.x.x.x.x.x.', 'x..x..x.x..x..x.'], notes: { root: 5, fifth: 1, octave: 5 }, approach: 0.3 },
    chords: { rhythms: ['..x...x...x...x.', 'x.....x...x.....'] },
    melody: { rhythms: ['x.......x...o...', 'x...o...x.......'], leap: 0.15, register: 'high' },
  },
  {
    id: 'reggae',
    name: 'Reggae',
    blurb: 'Roomy one-drop drums and offbeat keys',
    bpm: [72, 88],
    moods: ['chill', 'bright'],
    bars: 2,
    swing: 0.25,
    sounds: { drums: 'acoustic-drums', bass: 'Sub Bass', chords: 'Organ', melody: 'Marimba' },
    progressions: [
      [0, 3, 4, 0],
      [0, 5, 3, 4],
      [0, 3],
    ],
    drums: {
      lines: {
        kick: ['........x.......', '........x.....-.'],
        rim: ['........x.......'],
        hat: ['x.x.x.x.x.x.x.x.'],
        shaker: ['..o...o...o...o.'],
      },
      fills: { rim: '........x.....o.' },
    },
    bass: { rhythms: ['x.....x...x.....', 'x.......x...o...'], notes: { root: 7, fifth: 3, octave: 1 }, approach: 0.3 },
    chords: { rhythms: ['..x...x...x...x.'] },
    melody: { rhythms: ['....x.....o...x.', 'x.....o.........'], leap: 0.2, register: 'mid' },
  },
  {
    id: 'afro-pop',
    name: 'Afro Pop',
    blurb: 'Interlocking percussion and warm plucks',
    bpm: [96, 110],
    moods: ['bright', 'soulful'],
    bars: 4,
    swing: 0.2,
    sounds: { drums: 'electronic-drums', bass: 'Sub Bass', chords: 'Electric Piano', melody: 'Marimba' },
    progressions: [
      [0, 4, 5, 3],
      [0, 3, 5, 4],
      [5, 3, 0, 4],
    ],
    drums: {
      lines: {
        kick: ['x.....x...x.....', 'x.......x..x....'],
        rim: ['...x..x....x..x.'],
        hat: ['x.o.x.o.x.o.x.o.'],
        perc: ['..o..x....o..x..'],
      },
      fills: { hat: 'x.o.x.o.x.oxx.ox' },
    },
    bass: { rhythms: ['x.....x...o..x..', 'x..o....x..x....'], notes: { root: 7, fifth: 2, octave: 2 }, approach: 0.2 },
    chords: { rhythms: ['x.....x...x.....', 'x...............'] },
    melody: { rhythms: ['x..x..o...x..o..', '..x..x..o...x...'], leap: 0.2, register: 'mid' },
  },
  {
    id: 'ambient',
    name: 'Ambient',
    blurb: 'Slow evolving chords with a light pulse',
    bpm: [60, 76],
    moods: ['dreamy', 'chill'],
    bars: 4,
    swing: 0,
    sounds: { drums: 'electronic-drums', bass: 'Sub Bass', chords: 'Velvet Strings', melody: 'Bubble Keys' },
    progressions: [
      [0, 3],
      [5, 3],
      [0, 5, 3, 4],
    ],
    drums: { lines: { kick: ['x...............'], hat: ['....o.......o...'], rim: ['............-...'] } },
    bass: { rhythms: ['x...............'], notes: { root: 10, fifth: 1, octave: 0 }, approach: 0 },
    chords: { rhythms: ['x...............'] },
    melody: { rhythms: ['........o.......', 'x...........-...'], leap: 0.1, register: 'high' },
  },
  {
    id: 'arcade',
    name: 'Arcade',
    blurb: 'Pixel hooks and bouncing synth bass',
    bpm: [118, 142],
    moods: ['bright', 'epic'],
    bars: 2,
    swing: 0,
    sounds: { drums: 'electronic-drums', bass: 'Sub Bass', chords: 'Chiptune', melody: 'Chiptune' },
    progressions: [
      [0, 4, 5, 3],
      [5, 3, 0, 4],
      [0, 3, 4, 0],
    ],
    drums: {
      lines: { kick: ['x.......x.x.....', 'x...x...x...x...'], snare: ['....x.......x...'], hat: ['x.x.x.x.x.x.x.x.'] },
      fills: { snare: '....x.......x.xx' },
    },
    bass: { rhythms: ['x.x.x.x.x.x.x.x.', 'x..x..x.x..x..x.'], notes: { root: 5, fifth: 2, octave: 4 }, approach: 0.1 },
    chords: { rhythms: ['x.......x.......'] },
    melody: { rhythms: ['x.x.x.x.x.x.o.x.', 'x..x..x.x..x..x.'], leap: 0.4, register: 'high' },
  },
]
