import { EXTRA_STYLES } from './extraStyles'
import type { StyleDef } from './types'

/*
 * The style library. Each entry is pure data read by generator.ts — adding a
 * genre is adding an object here. Rhythm lines are one bar of 16ths:
 *   x always · o often · - sometimes · . never
 * Degrees are 0-based scale degrees of the project key (0 = home), so every
 * style works in every mood.
 *
 *            1   2   3   4          (beats)
 *            x...x...x...x...        (four on the floor)
 */
export const STYLES: StyleDef[] = [
  {
    id: 'boom-bap',
    name: 'Boom Bap',
    blurb: 'Dusty 90s hip-hop',
    bpm: [86, 94],
    moods: ['soulful', 'dark', 'chill'],
    bars: 2,
    swing: 0.55,
    sounds: { drums: 'acoustic-drums', bass: 'Bass', chords: 'Piano', melody: 'Pluck' },
    progressions: [[0, 5], [0, 3], [5, 3], [1, 0]],
    drums: {
      lines: {
        kick: ['x.....x...x.....', 'x......x..x..-..', 'x.....x.-.x.....'],
        snare: ['....x.......x...'],
        ghost: ['.......-......-.', '..-....-.-......'],
        hat: ['x.x.x.x.x.x.x.x.', 'x.x.x.xox.x.x.x.'],
        openHat: ['..............-.'],
      },
      fills: { snare: '....x.......x.oo' },
    },
    bass: { rhythms: ['x.....x...o.....', 'x.....o...x...-.'], notes: { root: 7, fifth: 2, octave: 1 }, approach: 0.3 },
    chords: { rhythms: ['x...............', 'x.......-.......'] },
    melody: { rhythms: ['x..-x.o...x..-..', '..x.o..x..o.x...'], leap: 0.15, register: 'mid' },
  },
  {
    id: 'lofi',
    name: 'Lo-fi',
    blurb: 'Late-night study beats',
    bpm: [70, 84],
    moods: ['chill', 'dreamy', 'soulful'],
    bars: 4,
    swing: 0.6,
    sounds: { drums: 'acoustic-drums', bass: 'Bass', chords: 'Piano', melody: 'Bell' },
    progressions: [[1, 4, 0, 5], [3, 2, 1, 0], [0, 5, 3, 4], [3, 4, 2, 5]],
    drums: {
      lines: {
        kick: ['x......-..x.....', 'x.......o.x.....'],
        rim: ['....x.......x...'],
        hat: ['x.o.x.o.x.o.x.o.', 'x.x.o.x.x.x.o.x.'],
        shaker: ['..-...-...-...-.'],
      },
      fills: { rim: '....x.......x.-x' },
    },
    bass: { rhythms: ['x.......o.......', 'x.....-.x.......'], notes: { root: 8, fifth: 2, octave: 1 }, approach: 0.4 },
    chords: { rhythms: ['x...............', 'x.......-...-...'] },
    melody: { rhythms: ['x...-..o....-...', '..o...x...-.o...'], leap: 0.2, register: 'high' },
  },
  {
    id: 'trap',
    name: 'Trap',
    blurb: 'Rolling hats, heavy low end',
    bpm: [132, 148],
    moods: ['dark', 'tense', 'epic'],
    bars: 2,
    swing: 0,
    sounds: { drums: 'electronic-drums', bass: 'Sub Bass', chords: 'Pad', melody: 'Bell' },
    progressions: [[0, 5], [0, 3, 5, 4], [0, 1], [5, 0]],
    drums: {
      lines: {
        kick: ['x......x..x.....', 'x.........x..-..', 'x......x...-.x..'],
        clap: ['........x.......'],
        hat: ['x.x.x.x.x.x.x.x.', 'xxx.x.x.xxx.x.xo', 'x.x.xxx.x.x.x-xx'],
        openHat: ['......-.......-.'],
      },
      fills: { hat: 'x.x.x.x.xxxxxxxx', kick: 'x......x..x.x.x.' },
    },
    bass: { rhythms: ['x......x..x.....', 'x.........x..-..'], notes: { root: 8, fifth: 1, octave: 2 }, approach: 0.15 },
    chords: { rhythms: ['x...............'] },
    melody: { rhythms: ['x.-.x.-.x.o.x.-.', 'x..x..x.x..x..x.'], leap: 0.25, register: 'high' },
  },
  {
    id: 'house',
    name: 'House',
    blurb: 'Four on the floor, organ stabs',
    bpm: [120, 126],
    moods: ['bright', 'soulful', 'dreamy'],
    bars: 2,
    swing: 0.15,
    sounds: { drums: 'electronic-drums', bass: 'Sub Bass', chords: 'Organ', melody: 'Pluck' },
    progressions: [[0, 5, 3, 4], [1, 4], [0, 3], [5, 3, 4, 0]],
    drums: {
      lines: {
        kick: ['x...x...x...x...'],
        clap: ['....x.......x...'],
        hat: ['..x...x...x...x.'],
        shaker: ['x-x-x-x-x-x-x-x-'],
        openHat: ['..-.......-.....'],
      },
      fills: { clap: '....x.......x.x.' },
    },
    bass: { rhythms: ['..x...x...x...x.', '..x..-x...x..-x.'], notes: { root: 6, fifth: 1, octave: 3 }, approach: 0.2 },
    chords: { rhythms: ['..x..x....x..x..', '..x...x...x..-x.'] },
    melody: { rhythms: ['x.o.x.o.-.x.o...', 'o.x...x.o.x...x.'], leap: 0.2, register: 'mid' },
  },
  {
    id: 'techno',
    name: 'Techno',
    blurb: 'Driving, hypnotic, minimal',
    bpm: [126, 134],
    moods: ['dark', 'tense'],
    bars: 1,
    swing: 0,
    sounds: { drums: 'electronic-drums', bass: 'Sub Bass', chords: 'Pad', melody: 'Pluck' },
    progressions: [[0], [0, 5], [0, 1]],
    drums: {
      lines: {
        kick: ['x...x...x...x...'],
        hat: ['..x...x...x...x.'],
        clap: ['....-.......x...'],
        perc: ['-..-..-..-..-...', '..-..-...-..-..-'],
        rim: ['.-...-.o...-...-'],
      },
    },
    bass: { rhythms: ['..x.x.x...x.x.x.', '.xx..xx..xx..xx.'], notes: { root: 9, fifth: 1, octave: 2 }, approach: 0 },
    chords: { rhythms: ['-.......-.......'] },
    melody: { rhythms: ['x.xx.x.xx.x.xx.x', 'x..x..x..x..x..x'], leap: 0.1, register: 'mid' },
  },
  {
    id: 'reggaeton',
    name: 'Reggaeton',
    blurb: 'The dembow bounce',
    bpm: [88, 98],
    moods: ['bright', 'dark', 'soulful'],
    bars: 2,
    swing: 0,
    sounds: { drums: 'electronic-drums', bass: 'Sub Bass', chords: 'Pluck', melody: 'Lead' },
    progressions: [[0, 5, 3, 4], [5, 3, 0, 4], [0, 4, 5, 3]],
    drums: {
      lines: {
        kick: ['x...x...x...x...'],
        snare: ['...x..x....x..x.'],
        hat: ['x.x.x.x.x.x.x.x.', 'x.xxx.x.x.xxx.x.'],
        perc: ['..-.......-.....'],
      },
    },
    bass: { rhythms: ['x..x..x.x..x..x.'], notes: { root: 7, fifth: 2, octave: 1 }, approach: 0.2 },
    chords: { rhythms: ['x..x..x.x..x..x.', 'x.......x.......'] },
    melody: { rhythms: ['x.x..x.x..x.x...', '..x.x..x.x..x.x.'], leap: 0.2, register: 'mid' },
  },
  {
    id: 'afrobeats',
    name: 'Afrobeats',
    blurb: 'Sunny, syncopated groove',
    bpm: [100, 112],
    moods: ['bright', 'soulful', 'chill'],
    bars: 2,
    swing: 0.2,
    sounds: { drums: 'electronic-drums', bass: 'Sub Bass', chords: 'Guitar', melody: 'Pluck' },
    progressions: [[0, 3, 4, 3], [0, 5, 3, 4], [1, 4, 0, 0]],
    drums: {
      lines: {
        kick: ['x..x..x...x..-..', 'x...x.x...x.....'],
        rim: ['...x..x....x..x.', '..x..x...x..x...'],
        clap: ['....x.......x...'],
        hat: ['x.xxx.xxx.xxx.xx', 'x-x-x-x-x-x-x-x-'],
        perc: ['......x.-.....x.'],
      },
    },
    bass: { rhythms: ['x..x..x...x..x..', 'x.....x.x..x....'], notes: { root: 6, fifth: 3, octave: 1 }, approach: 0.3 },
    chords: { rhythms: ['.x.x..x..x.x..x.', 'x..x..x.x..x..x.'] },
    melody: { rhythms: ['x.x..x..x..x.x..', '..x.x..x..x.x..x'], leap: 0.15, register: 'high' },
  },
  {
    id: 'funk',
    name: 'Funk',
    blurb: 'Tight pocket, busy bass',
    bpm: [96, 110],
    moods: ['bright', 'soulful', 'chill'],
    bars: 2,
    swing: 0.2,
    sounds: { drums: 'acoustic-drums', bass: 'Bass', chords: 'Organ', melody: 'Trumpet' },
    progressions: [[0, 3], [0], [0, 1], [0, 0, 3, 4]],
    drums: {
      lines: {
        kick: ['x.x...-..x.x....', 'x..x..x..x......'],
        snare: ['....x.......x...'],
        ghost: ['.-.....-.-...-..', '..-..-.....-..-.'],
        hat: ['xxxxxxxxxxxxxxxx', 'x.xxx.xxx.xxx.xx'],
        openHat: ['..........-.....'],
      },
      fills: { snare: '....x.......xxox' },
    },
    bass: { rhythms: ['x..x..x.x.-x..x.', 'x.xx..x..x.x..-x'], notes: { root: 5, fifth: 2, octave: 4 }, approach: 0.35 },
    chords: { rhythms: ['.x.x..x..x.x..x.', '..x..x....x..x..'] },
    melody: { rhythms: ['x..x.x....x.x...', '..x.xx....x..x..'], leap: 0.25, register: 'mid' },
  },
  {
    id: 'pop',
    name: 'Pop',
    blurb: 'Big, bright, singable',
    bpm: [100, 120],
    moods: ['bright', 'epic', 'dreamy'],
    bars: 4,
    swing: 0,
    sounds: { drums: 'acoustic-drums', bass: 'Bass', chords: 'Piano', melody: 'Lead' },
    progressions: [[0, 4, 5, 3], [5, 3, 0, 4], [0, 5, 3, 4], [3, 0, 4, 5]],
    drums: {
      lines: {
        kick: ['x.......x.x.....', 'x.....x.x.......'],
        snare: ['....x.......x...'],
        hat: ['x.x.x.x.x.x.x.x.'],
        crash: ['-...............'],
      },
      fills: { snare: '....x.......xxxx' },
    },
    bass: { rhythms: ['x.x.x.x.x.x.x.x.', 'x...x...x...x.x.'], notes: { root: 8, fifth: 1, octave: 1 }, approach: 0.2 },
    chords: { rhythms: ['x.......x.......', 'x..x..x...x.....'] },
    melody: { rhythms: ['x.x.x...x.x.o...', '..x.x.x.x...x...'], leap: 0.2, register: 'high' },
  },
  {
    id: 'rnb',
    name: 'R&B',
    blurb: 'Smooth, lush, laid-back',
    bpm: [66, 80],
    moods: ['soulful', 'chill', 'dreamy'],
    bars: 4,
    swing: 0.45,
    sounds: { drums: 'electronic-drums', bass: 'Sub Bass', chords: 'Pad', melody: 'Alto Saxophone' },
    progressions: [[3, 2, 1, 0], [0, 5, 1, 4], [1, 4, 0, 3]],
    drums: {
      lines: {
        kick: ['x......x.-x.....', 'x.......x..-....'],
        clap: ['....x.......x...'],
        hat: ['x.x.x.xox.x.x.x.', 'x.o.x.o.x.o.x.xx'],
        rim: ['.......-......-.'],
      },
    },
    bass: { rhythms: ['x.......x.-.....', 'x......-x.......'], notes: { root: 7, fifth: 2, octave: 1 }, approach: 0.4 },
    chords: { rhythms: ['x...............', 'x.......x.......'] },
    melody: { rhythms: ['x...o..-..x.....', '..x...o...x.-...'], leap: 0.25, register: 'mid' },
  },
  {
    id: 'synthwave',
    name: 'Synthwave',
    blurb: 'Neon 80s night drive',
    bpm: [96, 110],
    moods: ['dreamy', 'epic', 'dark'],
    bars: 4,
    swing: 0,
    sounds: { drums: 'electronic-drums', bass: 'Sub Bass', chords: 'Pad', melody: 'Lead' },
    progressions: [[0, 5, 3, 4], [5, 3, 0, 4], [0, 3, 5, 4]],
    drums: {
      lines: {
        kick: ['x.......x.......', 'x...x...x...x...'],
        snare: ['....x.......x...'],
        hat: ['x.x.x.x.x.x.x.x.', '..x...x...x...x.'],
        tom: ['..............-.'],
      },
      fills: { tom: '............xxxx' },
    },
    bass: { rhythms: ['xxxxxxxxxxxxxxxx', 'x.x.x.x.x.x.x.x.'], notes: { root: 5, fifth: 1, octave: 5 }, approach: 0 },
    chords: { rhythms: ['x...............'] },
    melody: { rhythms: ['x...x.x.x...x...', 'x.....x...x.x...'], leap: 0.15, register: 'high' },
  },
  {
    id: 'dnb',
    name: 'Drum & Bass',
    blurb: 'Fast breaks, deep bass',
    bpm: [170, 176],
    moods: ['dark', 'tense', 'epic'],
    bars: 2,
    swing: 0,
    sounds: { drums: 'electronic-drums', bass: 'Sub Bass', chords: 'Pad', melody: 'Pluck' },
    progressions: [[0, 5], [0, 3], [5, 4]],
    drums: {
      lines: {
        kick: ['x.........x.....', 'x......x..x.....'],
        snare: ['....x.......x...'],
        ghost: ['.......-.-......'],
        hat: ['x.x.x.x.x.x.x.x.', 'x.xxx.x.x.xxx.x.'],
      },
      fills: { snare: '....x.......x.xx' },
    },
    bass: { rhythms: ['x.......x.-.....', 'x.....x...x.....'], notes: { root: 8, fifth: 1, octave: 1 }, approach: 0.2 },
    chords: { rhythms: ['x...............'] },
    melody: { rhythms: ['x..x..x.....x...', '..x...x..x......'], leap: 0.2, register: 'mid' },
  },
  ...EXTRA_STYLES,
]

export function styleById(id: string): StyleDef | undefined {
  return STYLES.find((style) => style.id === id)
}
